#client
auth-server: http://localhost:8080

server:
  port: 8081
  context-path: /ui
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: UserArchievesapp
      client-secret: my-secret-token-to-change-in-production
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
logging:
  level:
    org.springframework.security: DEBUG
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


