server:
    port: 8082
    contextPath: /client

security:
    basic:
        enabled: false

config:
    oauth2:
        clientID: demo
        clientSecret: demo
        accessTokenUri: http://localhost:8080/oauth/token
        userAuthorizationUri: http://localhost:8080/oauth/authorize
        resourceURI: http://localhost:8080/me